import type { GalleryEntry } from "@/lib/gallery-types";

const DEFAULT_TITLES = [
  "Iteration I",
  "Iteration II",
  "Iteration III",
  "Iteration IV",
  "Iteration V",
] as const;

function iterations(sourceSlugs: readonly string[], group: GalleryEntry["group"], model: GalleryEntry["model"]) {
  return sourceSlugs.map((sourceSlug, index) => ({
    id: String(index + 1) as GalleryEntry["iterations"][number]["id"],
    title: DEFAULT_TITLES[index],
    sourceSlug,
    thumbnailPath: `/gallery-previews/${group}/${model}/${index + 1}.png`,
  }));
}

export const galleryManifest: GalleryEntry[] = [
  {
    group: "with-design-skill",
    groupLabel: "With Design Skill",
    model: "composer-1.5",
    modelLabel: "Composer 1.5",
    sourceDir: "with-frontend-design-skill/composer-1.5",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five expressive landing pages with heavier visual direction and per-iteration styling.",
    iterations: iterations(["1", "2", "3", "4", "5"], "with-design-skill", "composer-1.5"),
  },
  {
    group: "with-design-skill",
    groupLabel: "With Design Skill",
    model: "composer-2.0",
    modelLabel: "Composer 2.0",
    sourceDir: "with-frontend-design-skill/composer-2.0",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "A design-forward set of five branded landing explorations built around reusable brain themes.",
    iterations: iterations(["one", "two", "three", "four", "five"], "with-design-skill", "composer-2.0"),
  },
  {
    group: "with-design-skill",
    groupLabel: "With Design Skill",
    model: "gemini",
    modelLabel: "Gemini 3.1 Pro",
    sourceDir: "with-frontend-design-skill/gemini",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five interactive marketing pages with motion and a persistent floating switcher.",
    iterations: iterations(["1", "2", "3", "4", "5"], "with-design-skill", "gemini"),
  },
  {
    group: "with-design-skill",
    groupLabel: "With Design Skill",
    model: "gpt-5.4",
    modelLabel: "GPT-5.4",
    sourceDir: "with-frontend-design-skill/gpt-5.4",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "A highly art-directed set of five landing concepts with editorial typography and a drawer switcher.",
    iterations: iterations(["one", "two", "three", "four", "five"], "with-design-skill", "gpt-5.4"),
  },
  {
    group: "with-design-skill",
    groupLabel: "With Design Skill",
    model: "kimi-k-2.5",
    modelLabel: "Kimi K 2.5",
    sourceDir: "with-frontend-design-skill/kimi-k-2.5",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five client-heavy designs with a floating design switcher and strong visual contrast.",
    iterations: iterations(["one", "two", "three", "four", "five"], "with-design-skill", "kimi-k-2.5"),
  },
  {
    group: "with-design-skill",
    groupLabel: "With Design Skill",
    model: "opus-4.6",
    modelLabel: "Opus 4.6",
    sourceDir: "with-frontend-design-skill/opus-4.6/second-brain",
    sourceAppType: "vite",
    defaultIteration: "1",
    summary: "A Vite-based set of five animated routes ported into the unified gallery runtime.",
    iterations: iterations(["1", "2", "3", "4", "5"], "with-design-skill", "opus-4.6"),
  },
  {
    group: "without-design-skill",
    groupLabel: "Without Design Skill",
    model: "composer-1.5",
    modelLabel: "Composer 1.5",
    sourceDir: "without-frontend-design-skill/composer-1.5",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "A plainer five-page set with a shared switcher and lighter design experimentation.",
    iterations: iterations(["one", "two", "three", "four", "five"], "without-design-skill", "composer-1.5"),
  },
  {
    group: "without-design-skill",
    groupLabel: "Without Design Skill",
    model: "composer-2.0",
    modelLabel: "Composer 2.0",
    sourceDir: "without-frontend-design-skill/composer-2.0",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five route-grouped landing pages with a shared floating iteration switcher.",
    iterations: iterations(["one", "two", "three", "four", "five"], "without-design-skill", "composer-2.0"),
  },
  {
    group: "without-design-skill",
    groupLabel: "Without Design Skill",
    model: "gemini",
    modelLabel: "Gemini 3.1 Pro",
    sourceDir: "without-frontend-design-skill/gemini",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five simple but distinct landing pages navigated through a lightweight client navigation component.",
    iterations: iterations(["1", "2", "3", "4", "5"], "without-design-skill", "gemini"),
  },
  {
    group: "without-design-skill",
    groupLabel: "Without Design Skill",
    model: "gpt-5.4",
    modelLabel: "GPT-5.4",
    sourceDir: "without-frontend-design-skill/gpt-5.4",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five routes with a local iteration switcher and lighter polish than the design-skill version.",
    iterations: iterations(["one", "two", "three", "four", "five"], "without-design-skill", "gpt-5.4"),
  },
  {
    group: "without-design-skill",
    groupLabel: "Without Design Skill",
    model: "kimi-k-2.5",
    modelLabel: "Kimi K 2.5",
    sourceDir: "without-frontend-design-skill/kimi-k-2.5",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five designs grouped under a shared layout and floating switcher.",
    iterations: iterations(["one", "two", "three", "four", "five"], "without-design-skill", "kimi-k-2.5"),
  },
  {
    group: "without-design-skill",
    groupLabel: "Without Design Skill",
    model: "opus-4.6",
    modelLabel: "Opus 4.6",
    sourceDir: "without-frontend-design-skill/opus-4.6",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five conventional routes with a persistent switcher and a more restrained visual baseline.",
    iterations: iterations(["1", "2", "3", "4", "5"], "without-design-skill", "opus-4.6"),
  },
  {
    group: "miscellaneous",
    groupLabel: "Miscellaneous",
    model: "gpt-5.4",
    modelLabel: "GPT-5.4",
    sourceDir: "with-uncodexify-skill/gpt-5.4",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five uncodexify-generated Commonplace landings, integrated into the gallery without the original in-app route switcher.",
    iterations: [
      {
        id: "1",
        title: "Workspace",
        sourceSlug: "1",
        thumbnailPath: "/gallery-previews/miscellaneous/gpt-5.4/preview.svg",
      },
      {
        id: "2",
        title: "Library",
        sourceSlug: "2",
        thumbnailPath: "/gallery-previews/miscellaneous/gpt-5.4/preview.svg",
      },
      {
        id: "3",
        title: "Desk",
        sourceSlug: "3",
        thumbnailPath: "/gallery-previews/miscellaneous/gpt-5.4/preview.svg",
      },
      {
        id: "4",
        title: "Search",
        sourceSlug: "4",
        thumbnailPath: "/gallery-previews/miscellaneous/gpt-5.4/preview.svg",
      },
      {
        id: "5",
        title: "Review",
        sourceSlug: "5",
        thumbnailPath: "/gallery-previews/miscellaneous/gpt-5.4/preview.svg",
      },
    ],
  },
];

export function getGalleryEntry(group: string, model: string) {
  return galleryManifest.find((entry) => entry.group === group && entry.model === model);
}
