"use client";

import { useState } from "react";
import Image from "next/image";
import { Icon } from "../icons";
import { Action, Footer, SiteHeader } from "../studio";

function FieldNotebook() {
  const [tab, setTab] = useState("Life");
  const [checked, setChecked] = useState([true, false, false]);
  return <div className="five-notebook-scene"><div className="five-notebook-shadow" /><div className="five-notebook"><div className="notebook-rings" aria-hidden="true">{Array.from({ length: 9 }, (_, index) => <span key={index} />)}</div><div className="field-notebook-tabs" aria-label="Explore the notebook">{["Ideas", "Reading", "Life"].map((item) => <button key={item} className={`field-tab-${item.toLowerCase()} ${tab === item ? "active" : ""}`} onClick={() => setTab(item)} aria-pressed={tab === item}>{item}</button>)}</div><div className="field-page-content" key={tab}><div className="field-page-meta"><span>MY LITTLE SECOND BRAIN</span><Icon name="spark" size={18} /></div>
      {tab === "Life" && <><h2>A few good things.</h2><div className="field-page-top"><p>Salt air.<br />No alarm.<br /><em>Room to think.</em></p><div className="field-photo"><span className="paper-tape" /><Image src="/variants/with-design-skill/gpt-6-astra-preview/images/coast.jpg" alt="Waves washing onto a sunlit beach" width={800} height={530} preload /><span>the long way home ↗</span></div></div><div className="field-checklist"><p>Little things for later</p>{["Save a little piece of today", "Send Maya that article", "Take the long way home"].map((label, index) => <label key={label}><input type="checkbox" checked={checked[index]} onChange={() => setChecked(checked.map((item, checkIndex) => checkIndex === index ? !item : item))} /><span>{label}</span></label>)}</div><p className="field-bottom-thought">Turns out, the little things<br /><em>are the good stuff.</em><Icon name="sun" size={44} /></p></>}
      {tab === "Ideas" && <><h2>What if I made…</h2><p className="field-idea-intro">A field guide to my own<br /><em>little corner of the world.</em></p><div className="field-idea-map"><span>The neighborhood</span><i /><div><span>Quiet corners</span><span>Good coffee</span><span>Old bookshops</span></div></div><p className="field-idea-caption">One page. Five places.<br />A hand-drawn map.<br /><em>That’s a good place to start.</em></p><span className="field-idea-sticker">big ideas<br />start small. <Icon name="spark" size={24} /></span></>}
      {tab === "Reading" && <><h2>In very good company.</h2><p className="field-reading-intro">A few books to get a little lost in.</p><div className="field-book-list"><div><span className="field-book-cover">THE<br />CREATIVE<br /><em>ACT</em></span><p>The Creative Act<small>Rick Rubin</small><span>For paying attention.</span></p></div><div><span className="field-book-cover field-book-blue">A FIELD<br />GUIDE TO<br />GETTING<br /><em>LOST</em></span><p>A Field Guide to Getting Lost<small>Rebecca Solnit</small><span>For taking the long way.</span></p></div></div><p className="field-reading-note">Some books end.<br /><em>The good ones keep going.</em></p></>}
      <div className="field-page-footer"><Icon name="lock" size={12} /><span>Just for me, for now.</span><span>{tab === "Life" ? "12" : tab === "Ideas" ? "03" : "08"}</span></div></div></div><div className="five-curiosity-stamp"><span>FOR THE</span><Icon name="spark" size={30} /><strong>CURIOUS</strong><span>AT HEART</span></div><div className="five-notebook-annotation"><svg viewBox="0 0 90 55" fill="none" aria-hidden="true"><path d="M84 46C48 45 29 41 17 9m-4 19 3-23 17 11" stroke="currentColor" strokeWidth="2" /></svg><span>All your little worlds.<br />One happy place.</span></div></div>;
}

export default function Five() {
  return <div className="landing theme-five"><div className="five-yellow-stage"><SiteHeader variant="five" /><main id="main-content"><section className="five-hero page-width"><div className="five-hero-copy"><p className="five-eyebrow"><span>✳</span> A NOTE TO THE NOTE-TAKERS</p><h1>Keep the<br /><span>good stuff.<svg viewBox="0 0 580 35" fill="none" aria-hidden="true"><path d="M8 22C146 4 390 2 570 13M79 29c144-12 295-10 422-7" stroke="currentColor" strokeWidth="4" /></svg></span></h1><p>The ideas on the train. The books on your list.<br />The things that make you, you.<br /><strong>A second brain for a very full life.</strong></p><div className="hero-actions"><Action className="five-primary">Give it a little home <Icon name="arrow-up" size={19} /></Action><a href="#features" className="five-see-link">What’s inside? <Icon name="arrow-down" size={17} /></a></div><span className="five-free-note"><Icon name="check" size={15} /> Free to start. No perfect handwriting required.</span></div><FieldNotebook /></section><div className="five-bottom-strip"><span>LESS “WHERE DID I PUT THAT?”</span><span className="strip-asterisk">✳</span><span>MORE “OH, THAT’S A GOOD IDEA.”</span><span className="strip-asterisk">✳</span><span>A LITTLE HOME FOR A LOT OF YOU.</span></div></main></div>
    <section className="five-features page-width" id="features"><div className="five-section-heading"><div><p className="eyebrow">LIFE DOESN’T FIT IN ONE FOLDER.</p><h2>A pocket for every<br /><span>part of you.</span></h2></div><p>Your work brain. Your weekend brain.<br />Your “what if I just…” brain.<br />Bring the whole, interesting lot.</p></div><div className="five-pocket-grid"><article className="five-pocket pocket-blue"><div className="pocket-visual"><span className="pocket-small-note"><Icon name="book" size={26} /><strong>Read this.<br />Then read it again.</strong><span>the ever-growing list ↗</span></span><span className="pocket-label">THE RABBIT HOLES</span></div><h3>For what pulls you in.</h3><p>Good reads, big questions, and that article you’ve had open for three weeks.</p></article><article className="five-pocket pocket-pink"><div className="pocket-visual"><span className="pocket-small-note"><Icon name="sun" size={30} /><strong>Remember<br />this little moment.</strong><span>a thought from today ↗</span></span><span className="pocket-label">THE EVERYDAY</span></div><h3>For the here and now.</h3><p>A plan for dinner. A thought on a walk. Little things that deserve a little space.</p></article><article className="five-pocket pocket-green"><div className="pocket-visual"><span className="pocket-small-note"><Icon name="spark" size={29} /><strong>It might just<br />be something.</strong><span>one for someday ↗</span></span><span className="pocket-label">THE WHAT-IFS</span></div><h3>For what comes next.</h3><p>The side project. The faraway place. The first tiny piece of your next big thing.</p></article></div></section>
    <section className="five-philosophy" id="philosophy"><div className="page-width"><div className="five-philosophy-note"><span className="paper-tape" /><p>A friendly reminder:</p><h3>You don’t have to<br />keep it all<br /><em>in your head.</em></h3><Icon name="heart" size={29} /></div><div className="five-philosophy-copy"><p className="eyebrow">YOUR BRAIN CALLED. IT WANTS A BREATHER.</p><h2>A full life.<br />A little more<br /><em>headspace.</em></h2><p>Morrow keeps your notes, ideas, and bits of life together.<br />So you can get back to the interesting part: living it.</p><Action className="five-primary">Start keeping the good stuff <Icon name="arrow-up" size={19} /></Action></div></div></section><section className="five-final-word"><span>Here’s to a curious</span><p>morrow<span>✳</span></p><span>Make a little room for it.</span></section><Footer variant="five" line="For the note-takers. The daydreamers. You." /></div>;
}
