"use client";

import { useState } from "react";
import { Icon, MorrowMark } from "../icons";
import { Action, Footer, SiteHeader } from "../studio";
import { sampleNotes } from "../notebook";

function ConnectedWorkspace() {
  const [active, setActive] = useState(1);
  const [query, setQuery] = useState("");
  const [view, setView] = useState<"Notes" | "Connections">("Notes");
  const current = sampleNotes[active];
  const visible = sampleNotes.map((note, index) => ({ ...note, index })).filter((note) => `${note.title} ${note.content} ${note.tag}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="four-workspace">
    <div className="four-windowbar"><div className="window-dots"><span /><span /><span /></div><span>YOUR PERSONAL THINKING SPACE</span><span className="four-saved"><span className="status-dot" /> All thoughts accounted for</span></div>
    <div className="four-workspace-inner"><aside className="four-workspace-sidebar"><div className="four-space-name"><span>J</span><strong>Jamie’s space</strong><Icon name="chevron" size={12} /></div><label className="four-search"><Icon name="search" size={15} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Find a thought…" aria-label="Search connected example notes" /><kbd>⌘ K</kbd></label><div className="four-view-tabs">{(["Notes", "Connections"] as const).map((item) => <button className={view === item ? "active" : ""} key={item} onClick={() => setView(item)} aria-pressed={view === item}><Icon name={item === "Notes" ? "note" : "globe"} size={15} />{item}</button>)}</div><p className="four-ui-label">RECENT THOUGHTS</p><div className="four-note-links">{visible.map((note) => <button key={note.id} className={note.index === active ? "active" : ""} onClick={() => setActive(note.index)}><span className={`note-color note-color-${note.index}`} /><span>{note.title}</span></button>)}{visible.length === 0 && <p className="four-no-results">No matching thoughts.<br />Try another word.</p>}</div><Action className="four-new-note"><Icon name="plus" size={15} /> A new thought</Action><div className="four-sidebar-bottom"><Icon name="lock" size={13} /> Private, by nature.</div></aside>
    <article className="four-note-panel"><div className="four-note-breadcrumb">Your space <Icon name="chevron" size={10} /> {view.toLowerCase()}<span><Icon name="spark" size={14} /></span></div>{view === "Notes" ? <><div className="four-note-category"><span className={`note-color note-color-${active}`} />{current.tag}</div><h2>{current.title}</h2><div className="four-note-date">Last revisited {current.date.toLowerCase()} <span>·</span> A little clearer each time</div>{current.content.split("\n\n").map((paragraph, index) => <p className={index === 0 ? "four-note-intro" : ""} key={index}>{paragraph}</p>)}<div className="four-inline-link"><Icon name="link" size={14} /> This reminds me of <button onClick={() => setActive(active === 2 ? 0 : 2)}>{active === 2 ? "A slower kind of Sunday" : "A book worth keeping"}<Icon name="arrow-up" size={11} /></button></div></> : <><span className="four-note-category"><Icon name="globe" size={14} /> A bigger picture</span><h2>Follow a familiar thread.</h2><p className="four-note-intro">One thought has a way of leading to another. Pick a connection and see where it takes you.</p><div className="four-connection-list">{sampleNotes.filter((_, index) => index !== active).map((note) => <button key={note.id} onClick={() => { setActive(sampleNotes.findIndex((item) => item.id === note.id)); setView("Notes"); }}><Icon name="link" size={16} /><span>{note.title}<small>{note.tag}</small></span><Icon name="arrow-up" size={16} /></button>)}</div></>}</article>
    <aside className="four-graph-panel"><div className="four-graph-heading"><Icon name="globe" size={14} /> THE CONNECTIONS <span>5 notes</span></div><div className="four-graph"><svg viewBox="0 0 300 330" fill="none" aria-hidden="true"><path d="m145 152-62-87m62 87 85-46m-85 46 79 85m-79-85-78 71m78-71 7 117M83 65l147 41M67 223l157 14M83 65 67 223m163-117-6 131" stroke="#4B6179" strokeWidth=".8" /><circle cx="145" cy="152" r="91" stroke="#35475E" strokeDasharray="2 8" /><circle cx="145" cy="152" r="131" stroke="#293C50" strokeDasharray="2 8" /><path d="m145 152-62-87m62 87 85-46m-85 46 79 85m-79-85-78 71" stroke="#B8B9F3" strokeOpacity=".55" strokeWidth="1.2" /></svg>{sampleNotes.map((note, index) => <button key={note.id} className={`graph-point graph-point-${index} ${active === index ? "active" : ""}`} onClick={() => setActive(index)} aria-label={`Read ${note.title}`}><span className={`graph-orb orb-${index}`} /><span>{["A slower Sunday", "The creative process", "A book worth keeping", "Things I noticed", "A small project"][index]}</span></button>)}</div><div className="four-related-caption"><Icon name="spark" size={15} /><p>Good ideas rarely happen alone.<br /><span>Click a thought. Follow the thread.</span></p></div></aside></div><div className="four-workspace-status"><span><Icon name="link" size={12} /> Five thoughts. A world of possibilities.</span><span>SPACE TO THINK, ROOM TO CONNECT</span></div>
  </div>;
}

export default function Four() {
  return <div className="landing theme-four"><SiteHeader variant="four" /><main id="main-content"><section className="four-hero page-width"><div className="four-eyebrow"><span className="status-dot" /> YOUR MIND, WITH A LITTLE MORE CLARITY</div><h1>Everything you know.<br /><span>A little more connected.</span></h1><p>One thoughtful place for your notes, ideas, and discoveries.<br />Keep the context. Find the connections. Pick up where your mind left off.</p><div className="hero-actions"><Action className="four-primary">Find your train of thought <Icon name="arrow-up" size={18} /></Action><a className="four-demo-link" href="#workspace">Explore the workspace <Icon name="arrow-down" size={15} /></a></div><div className="four-hero-reassurance"><span><Icon name="check" size={13} /> Free to start</span><span><Icon name="lock" size={13} /> A private space</span><span><Icon name="spark" size={13} /> Made for your mind</span></div></section><section className="four-demo-section page-width" id="workspace"><ConnectedWorkspace /><div className="four-demo-caption"><span>THINK IN NOTES. SEE THE BIGGER PICTURE.</span><span>An interactive little glimpse. Make yourself at home.</span></div></section>
    <section className="four-features page-width" id="features"><div className="four-section-heading"><p className="eyebrow">A LITTLE LESS FRICTION. A LOT MORE THOUGHT.</p><h2>A place for the pieces.<br /><span>And the picture they make.</span></h2></div><div className="four-feature-grid"><article><span className="four-feature-icon"><Icon name="note" size={25} /></span><h3>Capture without the ceremony.</h3><p>Open a note and let the thought land. No perfect folder. No setup. Just a place to begin.</p><span className="four-feature-code">A THOUGHT → A NOTE</span></article><article><span className="four-feature-icon"><Icon name="globe" size={25} /></span><h3>Keep the context with it.</h3><p>A note means more beside a related idea. Keep the thread, so the next step comes a little easier.</p><span className="four-feature-code">A NOTE ↔ ANOTHER IDEA</span></article><article><span className="four-feature-icon"><Icon name="search" size={25} /></span><h3>Find your way back.</h3><p>A word is often all you remember. Search your space and let the rest come back to you.</p><span className="four-feature-code">A WORD → THAT ONE THOUGHT</span></article></div></section>
    <section className="four-philosophy page-width" id="philosophy"><div className="four-privacy-orbit"><div /><div /><div /><Icon name="lock" size={37} /></div><div><p className="eyebrow">A SPACE THAT’S TRULY YOURS</p><h2>Some thoughts are<br /><span>just for you.</span></h2><p>Your first drafts. Your big questions. Your not-quite-ready ideas.<br />A personal space should feel personal. This one does.</p><Action className="four-privacy-link" intent="privacy">A note on your privacy <Icon name="arrow-up" size={16} /></Action></div></section><section className="four-closing page-width"><MorrowMark size={51} /><h2>A clearer mind starts<br />with a little space.</h2><Action className="four-primary">Make it yours <Icon name="arrow-up" size={18} /></Action></section></main><Footer variant="four" line="Keep the thought. Find the thread." /></div>;
}
