"use client";

import { useState } from "react";
import Image from "next/image";
import { Icon, Sprout } from "../icons";
import { Action, Footer, SiteHeader } from "../studio";

const gardenNotes = [
  { label: "A LITTLE SEED", title: "What if I started\na tiny garden?", text: "A windowsill. A little sunlight. Something to care for that isn’t a screen.", tag: "just a thought", link: "Things I want to try", icon: "leaf" as const },
  { label: "TAKING ROOT", title: "The windowsill\nexperiment.", text: "Basil, mint, and one small tomato plant. A few notes about what’s growing.", tag: "a work in progress", link: "A slower kind of Sunday", icon: "sun" as const },
  { label: "SOMETHING TO KEEP", title: "Good things take\na little tending.", text: "A season of small observations. What the garden taught me about making room.", tag: "worth coming back to", link: "The creative process", icon: "book" as const },
];

export default function Three() {
  const [stage, setStage] = useState(0);
  return <div className="landing theme-three"><SiteHeader variant="three" /><main id="main-content">
    <section className="three-hero"><div className="three-hero-copy"><div className="three-eyebrow"><Sprout /> A GENTLER PLACE FOR YOUR THOUGHTS</div><h1>Let your mind<br /><em>wander.</em></h1><p>A home for the things you notice, the ideas you’re nurturing,<br className="desktop-break" /> and the connections that bloom along the way.</p><Action className="three-primary">Plant your first thought <Icon name="arrow-up" size={17} /></Action><span className="three-free-note">A little curiosity is all you need. Start free.</span></div><div className="three-side-thought">No pressure to<br />make sense.<br /><em>Not just yet.</em><svg viewBox="0 0 90 75" fill="none" aria-hidden="true"><path d="M13 5c-1 30 14 58 66 53M65 45l15 14-18 8" stroke="currentColor" strokeWidth="1.5" /></svg></div><Sprout className="three-hero-sprout" />
    <div className="three-garden-scene"><Image src="/variants/with-design-skill/gpt-6-astra-preview/images/garden.jpg" alt="Sunlight filling a green forest, with a path winding between the trees" fill sizes="100vw" preload /><div className="garden-image-shade" /><span className="garden-corner-label"><span className="status-dot" /> YOUR MIND IS A GARDEN, NOT A MACHINE.</span><div className="garden-observation"><Icon name="sun" size={18} /><span>Collected on a quiet morning.</span></div><div className="garden-note-card" key={stage}><div className="garden-note-meta"><Icon name={gardenNotes[stage].icon} size={17} /><span>{gardenNotes[stage].label}</span><span>↗</span></div><h2>{gardenNotes[stage].title}</h2><p>{gardenNotes[stage].text}</p><span className="garden-note-tag">{gardenNotes[stage].tag}</span><div className="garden-note-linked"><Icon name="link" size={14} />{gardenNotes[stage].link}</div></div><div className="garden-floating-tag"><Icon name="spark" size={15} /> Some ideas need a little sunshine.</div><div className="garden-small-card"><Sprout /><p>Leave a little room<br /><em>for what grows.</em></p><span>A NOTE TO MYSELF</span></div></div>
    <div className="garden-stage-picker" aria-label="Explore stages of a thought"><span>Every idea grows at its own pace.</span><div>{["Little seeds", "Taking root", "Evergreen"].map((label, index) => <button key={label} onClick={() => setStage(index)} className={stage === index ? "active" : ""} aria-pressed={stage === index}><Icon name={index === 0 ? "leaf" : index === 1 ? "sun" : "book"} size={15} />{label}</button>)}</div></div></section>
    <section className="three-features page-width" id="features"><div className="three-section-title"><p className="eyebrow">A LITTLE CARE GOES A LONG WAY</p><h2>From a passing thought<br />to <em>something that stays.</em></h2></div><div className="three-feature-grid"><article><div className="garden-feature-drawing seed-drawing"><span /><span /><span /></div><h3>Gather what catches your eye.</h3><p>A sentence. A photograph. A question with no answer yet. Keep the things that make you pause.</p></article><article><div className="garden-feature-drawing"><Sprout /></div><h3>Give your ideas room to grow.</h3><p>Come back with fresh eyes. Add a little more. Let your notes grow alongside your thinking.</p></article><article><div className="garden-feature-drawing flower-drawing"><svg viewBox="0 0 100 100" fill="none" aria-hidden="true"><path d="M50 52v40M50 75C24 78 21 65 27 60c13-2 23 8 23 15" /><path d="M50 20C19-3 13 29 31 35 1 45 22 66 42 50c2 31 30 24 21-1 25 17 40-10 12-20C91 7 61-1 50 20Z" /><circle cx="51" cy="35" r="9" /></svg></div><h3>Find the lovely connections.</h3><p>That old note and this new idea might have something in common. Follow the thread and see.</p></article></div></section>
    <section className="three-philosophy" id="philosophy"><div className="three-philosophy-inner"><Icon name="sun" size={38} /><p className="eyebrow">NO STREAKS. NO RUSH. JUST YOU.</p><h2>You don’t need to be<br />more productive.<br /><em>Just a little more curious.</em></h2><p>Morrow is a space to think at your own pace.<br />Some days that’s a whole page. Some days, a single word.<br />It all belongs.</p><Action className="three-primary">Make a little space for yourself <Icon name="arrow-up" size={17} /></Action></div></section></main><Footer variant="three" line="Good things grow from a little thought." /></div>;
}
