import Image from "next/image";
import Link from "next/link";
import { ArrowDownRight, ArrowRight, ArrowUpRight, Asterisk, BookmarkSimple, Feather, Flower, Infinity as InfinityIcon, Lightbulb, LockSimple, PencilSimple, Plus, Stack } from "@phosphor-icons/react/dist/ssr";
import { MobileMenu, Reveal, StartButton, ThoughtDemo } from "./experience";

function Artwork({ name, alt, className = "", hero = false }: { name: string; alt: string; className?: string; hero?: boolean }) {
  return <div className={`artwork ${className}`}><Image src={`/variants/with-taste-skill/gpt-6-astra/images/${name}.webp`} alt={alt} fill sizes={hero ? "(max-width: 767px) 100vw, 55vw" : "(max-width: 767px) 100vw, 42vw"} preload={hero} fetchPriority={hero ? "high" : undefined} /></div>;
}
function Header({ variant }: { variant: number }) {
  return <header className="site-header page-width"><Link href={`/${["one","two","three","four","five"][variant-1]}`} className="brand" aria-label="Morrow home"><Stack weight="regular" size={30} /><span>morrow<span className="brand-period">.</span></span></Link><nav className="desktop-nav" aria-label="Main navigation"><a href="#why">Why Morrow</a><a href="#how">How it works</a><a href="#questions">Questions</a></nav><div className="header-actions"><StartButton className="nav-cta" /><MobileMenu /></div></header>;
}
function HeroActions() { return <div className="hero-actions"><StartButton /><a className="button text-button" href="#how">Explore Morrow <ArrowRight size={18} /></a></div>; }
function Questions() {
  return <section id="questions" className="questions page-width"><Reveal><h2>A few things<br />you might wonder.</h2></Reveal><div className="faq-list"><details><summary>What can I keep in Morrow?<Plus size={19}/></summary><p>Ideas, reading notes, plans, links, and the little things you want to remember. Start with a sentence and follow it.</p></details><details><summary>Do I need to organize everything?<Plus size={19}/></summary><p>No perfect system required. Start writing, name your notes in your own words, and use search when you need them.</p></details><details><summary>Where are my notes saved?<Plus size={19}/></summary><p>This preview keeps notes in this browser. Export a Markdown copy to take them with you. Clearing browser data removes saved notes.</p></details><details><summary>Can I try it without an account?<Plus size={19}/></summary><p>Yes. Choose Start writing to open your notebook. Edit the sample notes or create something of your own.</p></details></div></section>;
}
function Footer({ phrase = "Make room for what's next." }: { phrase?: string }) {
  return <><section className="closing page-width"><Reveal><h2>{phrase}</h2><StartButton /></Reveal><Asterisk weight="light" className="closing-mark" aria-hidden="true" /></section><footer className="site-footer page-width"><Link className="brand" href="/with-taste-skill/gpt-6-astra/1"><Stack size={25}/><span>morrow.</span></Link><span>A home for your mind.</span><span>Keep something good.</span></footer></>;
}

export function One() {
  return <div className="site variant-1"><Header variant={1}/><main id="main"><section className="hero hero-one page-width"><Reveal className="hero-copy"><span className="eyebrow"><span className="eyebrow-rule"/> YOUR PERSONAL SECOND BRAIN</span><h1>Your mind,<br/><span>with more room.</span></h1><p>One home for your notes, passing thoughts, and big ideas. So you can make something of them.</p><HeroActions/></Reveal><Reveal className="hero-art" delay={.12}><Artwork name="paper" alt="A flowing loop sculpted from layers of paper with blue edges" hero/></Reveal></section><section className="purpose-bar page-width" id="why"><span>Less holding on.<br/><strong>More thinking freely.</strong></span><p>Some things are worth getting out of your head.<br/>And keeping somewhere you can find them.</p><ArrowDownRight size={32} weight="light"/></section><section className="how-section page-width" id="how"><Reveal><h2>A thought today.<br/><span>Something more tomorrow.</span></h2></Reveal><ThoughtDemo/></section><section className="collection-section page-width"><Reveal className="collection-heading"><h2>For all the things<br/>that make you, you.</h2><p>Book notes, half-formed ideas, places to go. There’s room for all of it.</p></Reveal><div className="collection-grid"><article className="collection-item collection-wide"><Artwork name="scrapbook" alt="A collection of photographs, paper, and small inspirations"/><h3>Your everyday discoveries <ArrowUpRight size={20}/></h3></article><article className="collection-item"><Artwork name="botanical" alt="Ginkgo leaves unfolding into the light"/><h3>Your growing ideas <ArrowUpRight size={20}/></h3></article></div></section><Questions/><Footer/></main></div>;
}

export function Two() {
  return <div className="site variant-2"><Header variant={2}/><main id="main"><section className="hero hero-two page-width"><Reveal className="hero-copy"><span className="eyebrow"><Flower size={19}/> A MORE NATURAL WAY TO THINK</span><h1>Let your<br/>ideas grow.</h1><p>A place to plant your thoughts, nurture your curiosity, and see what connects.</p><HeroActions/></Reveal><Reveal className="hero-art" delay={.12}><Artwork name="botanical" alt="Green and paper ginkgo leaves growing together on a branch" hero/></Reveal></section><section className="organic-statement page-width" id="why"><Flower size={42} weight="light"/><Reveal><h2>Your mind isn’t a filing cabinet.<br/><span>It’s a living, growing thing.</span></h2><p>Give your ideas a little space. Come back with fresh eyes.<br/>Let one thought lead you somewhere new.</p></Reveal></section><section className="garden-section page-width" id="how"><div className="garden-title"><h2>Good ideas<br/>take root here.</h2><p>You don’t need a perfect system.<br/>Just somewhere to begin.</p><Feather className="garden-icon" size={70} weight="thin"/></div><ThoughtDemo/></section><section className="organic-gallery page-width"><article><Artwork name="scrapbook" alt="Physical photographs collected into a personal moodboard"/><h3>Follow your curiosity.</h3><p>Gather the things that catch your eye. You can figure out why later.</p></article><article><Artwork name="paper" alt="Individual sheets of paper connected into one continuous loop"/><h3>See the bigger picture.</h3><p>Leave room between your notes for the next connection to happen.</p></article></section><Questions/><Footer phrase="Something good starts small."/></main></div>;
}

export function Three() {
  return <div className="site variant-3"><Header variant={3}/><main id="main"><section className="hero hero-three page-width"><Reveal className="hero-copy"><span className="eyebrow">BIG IDEAS NEED A PLACE TO LAND.</span><h1>GOOD IDEAS.<br/>ALL YOURS.</h1><p>A second brain for your first drafts, wild tangents, and next big thing.</p><HeroActions/></Reveal><Reveal className="hero-art" delay={.12}><Artwork name="chrome" alt="A polished chrome knot, a tangible tangle of connected ideas" hero/></Reveal></section><section className="bold-statement page-width" id="why"><Asterisk size={58} weight="bold"/><h2>LESS “WHERE DID I PUT THAT?”<br/><span>MORE “I’VE GOT AN IDEA.”</span></h2></section><section className="bold-how page-width" id="how"><Reveal><h2>CATCH IT.<br/>MAKE IT SOMETHING.</h2></Reveal><ThoughtDemo/></section><section className="bold-collection page-width"><div className="bold-collection-copy"><BookmarkSimple size={35}/><h2>YOUR BRAIN.<br/>UNCENSORED.</h2><p>Keep the rabbit holes, the rough edges, the ideas that don’t fit in a folder.</p><a href="#questions" className="button outline-button">Good questions <ArrowUpRight size={18}/></a></div><Artwork name="scrapbook" alt="An expressive arrangement of creative reference photographs"/><Artwork name="paper" alt="Sculptural paper sheets folded into a free flowing loop"/></section><Questions/><Footer phrase="GOT A THOUGHT? KEEP IT."/></main></div>;
}

export function Four() {
  return <div className="site variant-4"><Header variant={4}/><main id="main"><section className="hero hero-four page-width"><Reveal className="hero-copy"><span className="eyebrow"><Asterisk size={18}/> A HOME FOR YOUR CURIOUS MIND</span><h1>Keep what<br/>moves you.</h1><p>The little discoveries. The big what-ifs. A second brain for everything you want to come back to.</p><HeroActions/></Reveal><Reveal className="hero-art" delay={.12}><Artwork name="scrapbook" alt="A tactile collage of daisies, architecture, tulips, and ocean photographs" hero/></Reveal></section><section className="scrapbook-intro page-width" id="why"><p className="intro-sentence">Inspiration doesn’t arrive in folders.</p><Reveal><h2>Neither do you.</h2></Reveal><span>Save it now. Find the connection later.</span><Asterisk size={54} weight="thin"/></section><section className="scrapbook-how page-width" id="how"><Reveal><h2>A little collecting.<br/>A lot of possibility.</h2><p>Make a home for what catches your attention.</p></Reveal><ThoughtDemo/></section><section className="scrapbook-gallery page-width"><article className="scrapbook-photo"><Artwork name="botanical" alt="The delicate shapes and veins of fresh ginkgo leaves"/><h3>The things you notice.</h3></article><div className="scrapbook-note"><PencilSimple size={30} weight="light"/><h2>You don’t need<br/>to know what<br/>it’s for. Yet.</h2><p>Some ideas just need a place to wait.</p></div><article className="scrapbook-photo"><Artwork name="paper" alt="Pale paper folded into a flowing sculptural shape"/><h3>The things you imagine.</h3></article></section><Questions/><Footer phrase="Your next idea is in here."/></main></div>;
}

export function Five() {
  return <div className="site variant-5"><Header variant={5}/><main id="main"><section className="hero hero-five page-width"><Reveal className="hero-copy"><span className="eyebrow"><InfinityIcon size={21}/> THINK BEYOND THE TAB.</span><h1>A place for<br/>your whole mind.</h1><p>Turn scattered thoughts into a body of knowledge. Yours to build, connect, and return to.</p><HeroActions/></Reveal><Reveal className="hero-art" delay={.12}><Artwork name="glass" alt="Smoky glass plates orbiting a luminous pearl at their center" hero/></Reveal></section><section className="focus-principles page-width" id="why"><div><LockSimple size={22}/><span>Your own space.</span></div><div><Stack size={22}/><span>Everything in context.</span></div><div><Lightbulb size={22}/><span>Room for the next idea.</span></div></section><section className="focus-how page-width" id="how"><Reveal><h2>Build on what<br/>you already know.</h2><p>Your notes are a starting point.<br/>See where they take you.</p></Reveal><ThoughtDemo/></section><section className="focus-collection page-width"><div className="focus-title"><h2>Thinking doesn’t<br/>happen in a straight line.</h2><p>Your notebook shouldn’t make you.</p></div><Artwork name="paper" alt="Layers of paper forming a fluid, nonlinear sculpture"/><Artwork name="botanical" alt="Branching ginkgo leaves, each connected to a common stem"/><div className="focus-caption"><InfinityIcon size={36} weight="light"/><h3>Keep the context.<br/>Find the connection.</h3><p>The things you learn belong together.<br/>Give them a place to meet.</p></div></section><Questions/><Footer phrase="Clear a little headspace."/></main></div>;
}
